[project]
name = "minidl"
version = "0.0.1"
dependencies = [
    "numpy",
    "imgaug"
]

[project.optional-dependencies]
GPU = [
    "cupy",
]

[tool.setuptools.package-data]
"pkgname" = ["py.typed"]

[tool.setuptools.packages.find]
where = ["minidl"]